-- Appwrite Collection Setup for Content Planner
-- 
-- OPTION 1: Use the automated migration script (RECOMMENDED)
-- ---------------------------------------------------------
-- Run: node migrate-to-appwrite.js
-- This will:
--   1. Create the database and collection via API
--   2. Create all required attributes
--   3. Create indexes
--   4. Migrate data from Turso (if TURSO_DATABASE_URL is set)
--   5. Seed sample data if no migration source exists
--
-- Required environment variables:
--   APPWRITE_ENDPOINT    e.g. https://cloud.appwrite.io/v1
--   APPWRITE_PROJECT_ID  your Appwrite project ID
--   APPWRITE_API_KEY     your Appwrite API key (with database/admin permissions)
--
-- Optional for migration:
--   TURSO_DATABASE_URL   If set, will migrate data from Turso
--   TURSO_AUTH_TOKEN     Turso authentication token
--
-- OPTION 2: Manual setup via Appwrite Console
-- --------------------------------------------
-- 1. Create a Database in your Appwrite project (or use default)
-- 2. Create a Collection named "content_items" with these attributes:
--
-- Collection ID: content_items (or auto-generated)
-- Permissions: Set according to your security needs (API key used in backend has full access)
--
-- Document Attributes:
-- ---------------------
-- | Attribute     | Type      | Required | Default | Array |
-- |---------------|-----------|----------|---------|-------|
-- | day           | integer   | Yes      | -       | No    |
-- | audience      | string    | No       | -       | No    |
-- | raw           | string    | Yes      | -       | No    |
-- | refined       | string    | No       | -       | No    |
-- | platforms     | string    | No       | -       | No    | (JSON array as string)
-- | hook          | string    | No       | -       | No    |
-- | description   | string    | No       | -       | No    |
-- | cta           | string    | No       | -       | No    |
-- | hashtags      | string    | No       | -       | No    |
-- | design_spec   | string    | No       | -       | No    | (JSON object as string)
-- | design_image  | string    | No       | -       | No    | (base64 data URL)
--
-- Indexes:
-- --------
-- Create an index on 'day' for faster sorting (optional but recommended)
--
-- Note: Appwrite automatically adds $id, $createdAt, $updatedAt, $permissions metadata fields
--
-- Example API calls are handled by /api/content.js which uses the Appwrite REST API
